open-rpc/generator

- js/client-templated/exported-class.ts.tmpl
- js/src/index.js
- js/src/parse-schema.test.js
Tests will pass when https://github.com/open-rpc/examples/pull/4 is merged
> fix: updated for spec change

- templates/js/templated/exported-class.template.js
> fix: add paramStructure support

- README.md
> fix: updated broken path

- templates/js/templated/exported-class.template.js
fixes #40 
writing a test for this is a bit tricky right now so heres a gross manual test
> fix: no wrapping json response

- package-lock.json
- package.json
- templates/js/static/_package.json
- templates/js/static/tsconfig.json
- templates/js/templated/exported-class.template.js
> fix: get tests passing with stricter types

- package-lock.json
- package.json
- src/index.test.js
- templates/js/static/_package.json
- templates/js/static/tslint.json
- templates/js/templated/exported-class.template.js
> fix: tslint the generated package properly

- .circleci/config.yml
fixes https://github.com/open-rpc/generator-client/issues/102
> fix: run ci against fork prs

- package.json
> fix: copy templates into build properly

- README.md
This PR is an update for the root [generator-client/`README.md`] only
> fix: update generator-client/README.md

- templates/js/templated/exported-class.template.ts
> fix: use correct rpcParams passed in arguments

- package-lock.json
- src/cli.ts
> feat: add --version to cli

- src/cli.ts
> fix: output validation errors

- package-lock.json
- templates/typescript/static/_package.json
- templates/typescript/static/package-lock.json
- templates/typescript/templated/exported-class.template.ts
> fix: update client-js

- README.md
- package-lock.json
- package.json
- src/cli.ts
- src/index.test.ts
- src/index.ts
> fix: add ts-name config for package json name + rs-name for crate

- templates/rust/static/Cargo.toml
> fix: add description and license to Cargo.toml

- package-lock.json
- package.json
- src/index.test.ts
this gives us typescript optional param support
> fix: update typings

- package-lock.json
- package.json
fixes validation for optional params
> fix: update schema utils

- templates/rust/templated/client.template.ts
You're free to close this as I have not tested the changes
cc: @mersinvald
> fix: Remove unnecessary line

- templates/typescript/static/_package.json
- templates/typescript/static/package-lock.json
> fix: update schema utils to fix browser issue

- templates/client/typescript/_package.json
> fix: move type packages to non dev deps

- templates/client/typescript/_package.json
> fix: add typedoc configs to clean ui

- src/components/client.ts
> fix: lodash zipObject wrong order

- src/components/server.ts
> fix: server component package scripts merge
